services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:80"
    networks:
      - app-network
    volumes:
      - ./backend:/var/www/html

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "4200:80"
    networks:
      - app-network
    volumes:
      - ./frontend:/app

networks:
  app-network:
    driver: bridge
